defaults:
  - _self_
  # - config_override  # use it if you need to override

source_info:
  src: ${oc.env:VIDEO_SOURCE, "media/test.mov"}
  traffic_roi: []


detection:
  weight_pth: "weights/best_s.pt"
  tracker_pth: "configs/botsort.yaml"  # bytetrack.yaml, botsort.yaml
  classes_to_detect: [0, 1, 2]
  track_buffer: 15
  confidence: 0.2
  iou: 0.7
  imgsz: 640


show:
  show: True
  draw_roi: True
  draw_person_way: True
  output_size: [1920, 1080]
  fps_buffer: 15  # calculate if buffer > 1

web_mov:
  show: False
  host_ip: 0.0.0.0
  port: 9020
  fps: 12

video_writer:
  write: False
  output_path: "media/video_writer"
  segment_size: 14400
  bitrate: 500000
  skip_frames: 1
  fourcc: "XVID"
  fps: 30

notify:
  location_name: "Samarkand base street ..."
  location: [39.655221, 66.971076]

  buffer_size: 300  # FPS * second
  output_path: "media/detected_accident"

  chat_id: "10000000000"
  token: "10000000000:token"
