defaults:
  - _self_


source_info:
  src: ${oc.env:VIDEO_SOURCE, "media/1_all.mov"}


detection:
  weight_pth: "weights/yolo11m.pt"
  tracker_pth: "configs/botsort.yaml"  # bytetrack.yaml, botsort.yaml
  classes_to_detect: [0, 2, 5, 7, 9]
  confidence: 0.2
  iou: 0.7
  imgsz: 640


show:
  show: True
  fps_buffer: 15  # calculate if buffer > 1
